[package]
name = "math_universe_keirin"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = { workspace = true }
pyo3 = { workspace = true, optional = true }

[features]
python = ["dep:pyo3"]
